# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and push dev

on:
  push:
    branches: [master]

jobs:
  checkArtifact:
    if: ${{github.event.pull_request.merged == true}}
    env:
      CLEAN_INSTALL: false
    name: Check artifact downloading
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - run: env
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        env:
          DIST_NAME: ${{ format('build2_{0}', github.event.pull_request.head.sha) }}
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: lint.yaml
          name: ${{ env.DIST_NAME }}
          path: build
      - name: Mark Clean Install
        if: ${{!contains(find . -maxdepth 1 -type d -printf '%f\n', 'dist') }}
        run: CLEAN_INSTALL="true"

      - name: Read actions/cache
        if: ${{ env.CLEAN_INSTALL == true }}
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: ${{ env.CLEAN_INSTALL == true }}
        run: yarn install --frozen-lockfile
      - name: Ls
        run: "ls -l"
