# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and push dev

on:
  pull_request:
    types: [closed]

jobs:
  checkArtifact:
    if: ${{github.event.pull_request.merged == true}}
    name: Check artifact downloading
    runs-on: ubuntu-latest
    env:
      DIST_NAME: ${{ format('dist_{0}', github.event.pull_request.head.sha) }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - run: env
      - name: Cache node modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        env:
          DIST_NAME: ${{ format('dist_{0}', github.event.pull_request.head.sha) }}
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: lint.yaml
          name: ${{ env.DIST_NAME }}
          path: dist
      - name: Ls
        run: "ls -l"
