name: Lint
on: [pull_request]
jobs:
  dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install  --frozen-lockfile

  lint:
    needs: dependencies
    name: Start es-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: eslint:ci