name: Lint2
on: [pull_request]
jobs:
  build:
    name: lint project
    runs-on: ubuntu-latest
    env:
      working-directory: front

    steps:
      - uses: actions/checkout@v1
        with:
          cmd: eslint:github-action
