name: Lint
on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: OrlovAlexei/githubActions/.github/actions/goodbye@master
        with:
          who-to-greet: "Me and me "
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  build:
    runs-on: ubuntu-latest
    env:
      DIST_NAME: ${{ format('dist_{0}', github.event.pull_request.head.sha) }}
    steps:
      - uses: actions/checkout@v1
      - name: Read cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Build app
        run: tsc
      - run: env
      - name: Upload dist folder
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.DIST_NAME }}
          path: dist/
          retention-days: 5
