name: Lint2
on: [pull_request]
jobs:
  build:
    name: lint project
    runs-on: ubuntu-latest
    env:
      working-directory: front

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{ env.working-directory }}
      - name: linting...
        run: yarn eslint:github-action
        working-directory: ${{ env.working-directory }}
