name: Lint
on: [pull_request]
jobs:
  build:
    name: lint project
    runs-on: ubuntu-latest
    env:
      working-directory: front

    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: eslint:github-action
