name: Lint
on: [pull_request]

jobs:
  # hello_world_job:
  #   runs-on: ubuntu-latest
  #   name: A job to say hello
  #   steps:
  #     - uses: actions/checkout@v2
  #     - id: foo
  #       uses: OrlovAlexei/githubActions/.github/actions/goodbye@master
  #       with:
  #         who-to-greet: "Me and me "
  #     - run: echo random-number ${{ steps.foo.outputs.random-number }}
  #       shell: bash

  build:
    runs-on: ubuntu-latest
    env:
      DIST_NAME: ${{ format('build_{0}', github.event.pull_request.head.sha) }}
    steps:
      - uses: actions/checkout@v1
      - run: env
      - name: Read cache node modules
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install deps
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - name: Build app
        run: yarn build
      - name: Upload build folder
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.DIST_NAME }}
          path: build/
          retention-days: 5

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Read cache node modules
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install deps
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - name: Install cypress binary
        run: yarn cypress install
      - uses: actions/download-artifact@v2
        env:
          DIST_NAME: ${{ format('build_{0}', github.event.pull_request.head.sha) }}
        with:
          name: ${{ env.DIST_NAME }}
          path: build
      - name: Build docker image
        run: docker build -t multifrontend .
      - name: Run docker image
        run: docker run -d -p 8081:80 --rm --name insmfront -e ENV=SuperEnvFromActions -e BASE_URL=https://dev.oprosso.ru/ap/2222i  multifrontend
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          headless: true
          install: false
          browser: chrome
          # build: yarn build:dev
          # start: yarn serve -l 8081
