name: Lint2
on: [pull_request]
jobs:
  build:
    name: lint project
    runs-on: ubuntu-latest
    env:
      working-directory: front

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{ env.working-directory }}
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run reviewdog
        working-directory: ${{ env.working-directory }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: reviewdog -reporter=github-pr-review -runners=eslint
