name: Run eslint with reviewdog
on: [pull_request]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    env:
      working-directory: front
    steps:
      - uses: actions/checkout@v1
      - name: Install deps2
        run: yarn install
        working-directory: ${{ env.working-directory }}
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: reviewdog -reporter=github-pr-review -name="eslint"
