name: Lint2
on: [pull_request]
jobs:
  build:
    name: lint project
    runs-on: ubuntu-latest
    env:
      working-directory: front

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{ env.working-directory }}

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1

      - name: Run reviewdog
        working-directory: ${{ env.working-directory }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn eslint src |  reviewdog -f=eslint -reporter=github-pr-check
